name: Deploy Azure Resource workflow

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pages: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Login to Azure
      uses: Azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
    - name: Deploy Dev Environment to Azure
      uses: Azure/arm-deploy@v2
      with:
        # Provide the scope of the deployment. Valid values are: 'resourcegroup', 'tenant', 'managementgroup', 'subscription'
        scope: resourcegroup        
        resourceGroupName: ${{ secrets.AZURE_RG }}
        # Specify the path or URL to the Azure Resource Manager template.
        template: ./InfrastructureAsCode/main.bicep        
        # Specifies the name of the resource group deployment to create.
        deploymentName: ${{ secrets.AZURE_RG }}
        # Supply deployment parameter values.
        parameters: environment=dev
      
              


    
