name: first-workflow
on: 
  workflow_dispatch:
  issues:
    types:
    - opened

env:
  env_variable_for_test: "Environment variable to test"
  
jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    steps:
    - name: task1
      run: echo "Step 1 complete! $env_variable_for_test"
    - name: task2
      run: echo "Step 2 complete! $env_variable_for_test"
  job2:
    name: Job2
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - name: Cowsays
      # You may pin to the exact commit or the version.
      # uses: mscoutermarsh/cowsays-action@822c8424f7ebc1f4c8b86b0bcb11e4051b7f42e2
      uses: mscoutermarsh/cowsays-action@v1
      with:
      # What does the cow say?
        text: "Ready for prod–ship it! $env_variable_for_test" # optional, default is Ship it!!!!!
        # Color of your cow
        color: magenta  # optional, default is white
          
    

